@echo off
echo Initializing Git repository...
git init
echo.
echo Adding files...
git add .
echo.
echo Committing files...
git commit -m "Initial commit of AiMystara website"
echo.
echo Renaming branch to main...
git branch -M main
echo.
echo Adding remote origin...
git remote add origin https://github.com/dharmik107/AiMystara.git
echo.
echo Pushing to GitHub...
git push -u origin main
echo.
echo Done! checking status...
git status
pause
